SELECT SCHEMA_NAME, SUM(SEGMENT_SIZE) / (1024.0 * 1024.0 * 1024.0)  TABLE_SIZE
FROM (
    SELECT
        ds.owner SCHEMA_NAME,
        BYTES SEGMENT_SIZE
    from DBA_SEGMENTS ds
    LEFT JOIN DBA_LOBS dl ON dl.SEGMENT_NAME = ds.SEGMENT_NAME AND dl.OWNER = ds.OWNER
    WHERE SEGMENT_TYPE IN ('TABLE', 'LOBSEGMENT', 'CLUSTER', 'TABLE PARTITION',
                           'LOB PARTITION', 'NESTED TABLE', 'TABLE SUBPARTITION', 'XMLTYPE TABLE',
                           'SECUREFILE LOBSEGMENT', 'SHADOW TABLE')
    )
GROUP BY SCHEMA_NAME;
